<?php
/**
 * Search helpers.
 *
 * @package chassesautresor.com
 */

defined('ABSPATH') || exit;

/**
 * Retrieves the raw search term associated with a context key.
 *
 * @param string $key Context identifier.
 *
 * @return string
 */
function ca_get_search_term(string $key): string
{
    $context   = ca_resolve_search_context($key);
    $parameter = $context['parameter'] ?? sanitize_key($key);

    $raw = null;

    if (isset($_GET['search'][ $parameter ])) {
        $raw = $_GET['search'][ $parameter ];
    } elseif (isset($_POST['search'][ $parameter ])) {
        $raw = $_POST['search'][ $parameter ];
    } elseif (wp_doing_ajax()) {
        $payload = filter_input(INPUT_POST, 'search', FILTER_DEFAULT, FILTER_REQUIRE_ARRAY);

        if (is_array($payload) && isset($payload[ $parameter ])) {
            $raw = $payload[ $parameter ];
        }
    }

    if (is_array($raw)) {
        $raw = reset($raw);
    }

    if (null === $raw) {
        return '';
    }

    $term = trim((string) wp_unslash($raw));

    /**
     * Filters the normalized search term before it is returned.
     *
     * @param string $term      Search term.
     * @param string $key       Context identifier.
     * @param string $parameter Query parameter name.
     */
    return (string) apply_filters('ca_get_search_term', $term, $key, $parameter);
}

/**
 * Applies the current search term to the provided query arguments.
 *
 * For SQL-based contexts, the function appends a prepared WHERE clause. For
 * WP_Query contexts, the function extends the meta_query array.
 *
 * @param string            $key        Context identifier.
 * @param array|string      $base_query Existing query arguments or SQL string.
 * @param string|null       $term       Optional search term override.
 *
 * @return array|string
 */
function ca_apply_search_filters(string $key, $base_query, ?string $term = null)
{
    $context = ca_resolve_search_context($key);

    if (empty($context)) {
        return $base_query;
    }

    if (null === $term) {
        $term = ca_get_search_term($key);
    }

    $term = trim((string) $term);

    if ('' === $term) {
        return $base_query;
    }

    global $wpdb;

    $like_term = '%' . $wpdb->esc_like($term) . '%';
    $fields    = $context['fields'] ?? [];

    if (!empty($fields['sql'])) {
        $clauses = [];

        foreach ($fields['sql'] as $field) {
            $clauses[] = $wpdb->prepare("{$field} LIKE %s", $like_term);
        }

        if (empty($clauses)) {
            return $base_query;
        }

        $clause = '(' . implode(' OR ', $clauses) . ')';

        if (is_array($base_query)) {
            if (!isset($base_query['where'])) {
                $base_query['where'] = [];
            }

            if (is_string($base_query['where'])) {
                $base_query['where'] = [$base_query['where']];
            }

            if (!is_array($base_query['where'])) {
                $base_query['where'] = [];
            }

            $base_query['where'][] = $clause;

            /**
             * Filters the SQL fragments generated by the search helper.
             *
             * @param array  $base_query Query arguments augmented with search clauses.
             * @param string $key        Context identifier.
             * @param string $term       Search term.
             * @param array  $context    Registered context definition.
             */
            return apply_filters('ca_apply_search_filters_sql', $base_query, $key, $term, $context);
        }

        if (is_string($base_query)) {
            $glue = stripos($base_query, 'WHERE') !== false ? ' AND ' : ' WHERE ';
            $query = $base_query . $glue . $clause;

            return apply_filters('ca_apply_search_filters_sql_string', $query, $key, $term, $context);
        }

        $fragments = [
            'where' => $clause,
        ];

        return apply_filters('ca_apply_search_filters_sql_fragment', $fragments, $key, $term, $context);
    }

    if (!empty($fields['wp_query'])) {
        if (!is_array($base_query)) {
            $base_query = [];
        }

        $meta_query = $base_query['meta_query'] ?? [];
        $meta_query = is_array($meta_query) ? $meta_query : [];
        $fragments  = [];

        foreach ($fields['wp_query'] as $field) {
            if (is_string($field)) {
                $fragments[] = [
                    'key'     => $field,
                    'value'   => $like_term,
                    'compare' => 'LIKE',
                ];
                continue;
            }

            if (is_array($field) && isset($field['key'])) {
                $fragments[] = array_merge(
                    [
                        'value'   => $like_term,
                        'compare' => 'LIKE',
                    ],
                    $field
                );
            }
        }

        if (empty($fragments)) {
            return $base_query;
        }

        $meta_query = array_merge($meta_query, $fragments);

        if (count(array_filter(array_keys($meta_query), 'is_string')) === 0 && count($meta_query) > 1) {
            $meta_query = array_merge(['relation' => 'AND'], $meta_query);
        } elseif (!isset($meta_query['relation']) && count($meta_query) > 1) {
            $meta_query['relation'] = 'AND';
        }

        $base_query['meta_query'] = $meta_query;

        /**
         * Filters the WP_Query arguments generated by the search helper.
         *
         * @param array  $base_query Query arguments augmented with search clauses.
         * @param string $key        Context identifier.
         * @param string $term       Search term.
         * @param array  $context    Registered context definition.
         */
        return apply_filters('ca_apply_search_filters_wp_query', $base_query, $key, $term, $context);
    }

    return $base_query;
}
